name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/chechkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cacheo/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Test PlatformIO
      run: pio test -e native